<a href="https://colab.research.google.com/github/ThitiwatJtrsn/multivariate/blob/main/Function_Numpy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Function

```python
def function_name(_Input_):
    do_something with _Input_ to produce _Output_
    return _Output_
```

function มีส่วนสำคัญทั้งหมด 4 ส่วน
1. บอก python ว่าเราจะเขียนฟังก์ชั่น ชื่ออะไร def function_name(): (ขาดไม่ได้)

2. กำหนดตัวแปรที่จะเป็น input Input (ขาดได้)

3. ส่วนประมวลผล do_something with Input to get Output (ขาดไม่ได้)

4. ส่วน output return Output(ขาดได้)
เราใช้ เว้นวรรค (indent) เพื่อบอกขอบเขตของ code



#### สร้างฟังก์ชั่น

In [ ]:
def print_name(name,surname,ID):
    st = f'ชื่อ {name} นามสกุล {surname} ID {ID}'
    return st
print('outside function')

outside function


In [ ]:
def print_name(name,surname,ID) :
        st = f'ชื่อ {name} นามสกุล {surname} ID {ID}'
        return st

In [ ]:
print_name('ฐิติวัฒน์','จันทรเสนา','623021047-5')

'ชื่อ ฐิติวัฒน์ นามสกุล จันทรเสนา ID 623021047-5'

In [ ]:
output_string = print_name('ฐิติวัฒน์','จันทรเสนา','623021047-5')
print(output_string)

ชื่อ ฐิติวัฒน์ นามสกุล จันทรเสนา ID 623021047-5


ฟังก์ชั่นไม่จำเป็นต้องมี input

In [ ]:
def Pi():
    return 3.14159265 

In [ ]:
#คำนวณพื้นที่วงกลมที่มีขนาดเส้นผ่านศูนย์กลางเท่ากับ 3
Pi()*(1.5**2)

7.0685834625

In [ ]:
def print_my_name():
    print('ฐิติวัฒน์ 623021047-5')

In [ ]:
print_my_name()

ฐิติวัฒน์ 623021047-5


### 1. input ของ function ใน python มีสองแบบ ```input ที่จำเป็นต้องใส่``` กับ ```input ที่ไม่จำเป็นต้องใส่ (มีค่า default)```

### 2. เราต้องเรียง input ที่จำเป็นต้องใส่ขึ้นก่อน

In [ ]:
def print_2lines_default(name,surname,ID,grade='A'):
    st = f'ชื่อ {name} นามสกุล {surname} รหัส {ID}'
    print(st)
    st2 = f'เกรดวิชา Multivariate >>> {grade}'
    print(st2)

In [ ]:
print_2lines_default('ฐิติวัฒน์','จันทรเสนา','623021047-5')

ชื่อ ฐิติวัฒน์ นามสกุล จันทรเสนา รหัส 623021047-5
เกรดวิชา Multivariate >>> A


In [ ]:
print_2lines_default('ฐิติวัฒน์','จันทรเสนา','623021047-5','A')

ชื่อ ฐิติวัฒน์ นามสกุล จันทรเสนา รหัส 623021047-5
เกรดวิชา Multivariate >>> A


เราสามารถเรียกฟังก์ชั่นโดยใช้ชื่อตัวแปรของฟังก์ชั่นช่วยได้

HW3 ให้เขียน function คำนวณจำนวนวินาทีจาก เวลาต่อไปนี้

'14-15-31'

'13-00-01'

'05-49-44'

'00-00-16'

และ print ให้สวยงาม

In [ ]:
def function_time(time):
    st = time.split('-')
    ans = int(st[0]) * 3600 + int(st[1]) * 60 + int(st[2]) 
    print(f'คำนวณจำนวนวินาทีจาก {time} จะเท่ากับ {ans} วินาที')

In [ ]:
function_time('14-15-31')

คำนวณจำนวนวินาทีจาก 14-15-31 จะเท่ากับ 51331 วินาที


In [ ]:
function_time('13-00-01')

คำนวณจำนวนวินาทีจาก 13-00-01 จะเท่ากับ 46801 วินาที


In [ ]:
function_time('05-49-44')

คำนวณจำนวนวินาทีจาก 05-49-44 จะเท่ากับ 20984 วินาที


In [ ]:
function_time('00-00-16')

คำนวณจำนวนวินาทีจาก 00-00-16 จะเท่ากับ 16 วินาที


Numpy -> package สำหรับจัดการกับ Array ที่เป็นตัวเลข (Matrix)

Num + py -> Number-Numerical + python

การใช้ package
1. ```import``` ```ชื่อ package``` #เรียกใช้ package
2. ```ชื่อ package```.```ชื่อฟังก์ชั่น``` #เรียกใช้ function 

In [1]:
import numpy

data structure -> array

สร้าง array (numpy array)

In [2]:
mat_ex1 = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(mat_ex1)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]


ชี้ค่าใน numpy array

In [3]:
mat_ex1[1,1] #[แถว,หลัก]

0.1

ถ้าไม่มี numpy array

In [4]:
list_ex1 = [[5.2,3.0,4.5],[9.1,0.1,0.3]]
print(list_ex1)

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3]]


In [5]:
list_ex1[1,1]

TypeError: ignored

In [6]:
list_ex1[1][1]

0.1

In [7]:
print(list_ex1)
a = list_ex1[1]
print(a)
print(a[1])

[[5.2, 3.0, 4.5], [9.1, 0.1, 0.3]]
[9.1, 0.1, 0.3]
0.1


Matrix Operations

data 2 แบบ -> matrix (2D array), scalar (ตัวเลขค่าคงที่)

In [8]:
mat_ex1 = numpy.array([[5.2,3.0,4.5],[9.1,0.1,0.3]])
print(mat_ex1)
mat_ex2 = numpy.array([[2,3.7,5.9],[91,1.5,7.3]])
print(mat_ex2)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
[[ 2.   3.7  5.9]
 [91.   1.5  7.3]]


## บวกกับลบ matrix เอาตัวเลขตำแหน่งเดียวกันมาบวกหรือลบกัน
(หน้าตาของ matrix ต้องเหมือนกัน)

In [9]:
mat_ex0 = numpy.array([[1,2],[3,4]])
print(mat_ex0)

[[1 2]
 [3 4]]


In [10]:
mat_ex3 = mat_ex1 + mat_ex2
print(mat_ex3)
mat_ex4 = mat_ex1 - mat_ex2
print(mat_ex4)

[[  7.2   6.7  10.4]
 [100.1   1.6   7.6]]
[[  3.2  -0.7  -1.4]
 [-81.9  -1.4  -7. ]]


In [11]:
mat_ex1 + mat_ex0

ValueError: ignored

การตรวจสอบขนาดของ matrix

In [12]:
mat_ex3.shape

(2, 3)

In [13]:
mat_ex3.shape[0]

2

## คูณ matrix

In [14]:
print(mat_ex1)
print(mat_ex1.shape)
print(mat_ex2)
print(mat_ex2.shape)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
(2, 3)
[[ 2.   3.7  5.9]
 [91.   1.5  7.3]]
(2, 3)


In [15]:
mat_ex1 * mat_ex2

array([[1.040e+01, 1.110e+01, 2.655e+01],
       [8.281e+02, 1.500e-01, 2.190e+00]])

## การคูณ matrix (แถวคูณหลัก)
(หลักของ Matrix ตัวข้างหน้า ต้องเท่ากับแถวของ Matrix ตัวข้างหลัง)

(AAA,x) . (x,ZZZ) = (AAA,ZZZ)

In [16]:
numpy.dot(mat_ex1,mat_ex2)

ValueError: ignored

In [17]:
print(mat_ex1)
print(mat_ex1.shape)
print(mat_ex2)
print(mat_ex2.shape)

[[5.2 3.  4.5]
 [9.1 0.1 0.3]]
(2, 3)
[[ 2.   3.7  5.9]
 [91.   1.5  7.3]]
(2, 3)


# Transpose กลับแถวเป็นหลักกลับหลักเป็นแถว

```matrix.T```

In [18]:
print(mat_ex2)
print(mat_ex2.shape)

[[ 2.   3.7  5.9]
 [91.   1.5  7.3]]
(2, 3)


In [19]:
print(mat_ex2.T)
print(mat_ex2.T.shape)

[[ 2.  91. ]
 [ 3.7  1.5]
 [ 5.9  7.3]]
(3, 2)


In [20]:
numpy.dot(mat_ex1,mat_ex2.T) #(2,3).(3,2)

array([[ 48.05, 510.55],
       [ 20.34, 830.44]])

In [21]:
numpy.dot(mat_ex1.T,mat_ex2) #(3,2).(2,3) = (3,3)

array([[838.5 ,  32.89,  97.11],
       [ 15.1 ,  11.25,  18.43],
       [ 36.3 ,  17.1 ,  28.74]])

HW4 อธิบายการหา Determinant และ Inverse matrix (รูป และ คำอธิบาย)